#!/usr/bin/python
import time
import sys
import sqlite3 as lite
from twitter import *
from datetime import datetime, date


token = open('../../twitter/token', 'r').readline().strip()
token_secret = open('../../twitter/token_secret', 'r').readline().strip()
consumer_key = open('../../twitter/consumer_key', 'r').readline().strip()
consumer_secret = open('../../twitter/consumer_secret', 'r').readline().strip()

dataStream = "../Data/sensor_stream.db"

refreshSec = 600

def runReport():
	try:
		con = lite.connect(dataStream)
		cur = con.cursor()

		timestamp = int(time.time()) - refreshSec
		cur.execute("select avg(temperature), avg(humidity) from sensor_log where time_stamp > ?", [timestamp])
		result = cur.fetchall()
		T = result[0][0]
		RH = result[0][1]

		tweet = "Temperature: {:10.1f}, Humidity: {:10.1f}".format(T, RH)
		postTweet (tweet)
	finally:
		if(con != None):
			con.close()
def postTweet(tweet):
	print tweet
	t = Twitter(auth=OAuth(
			consumer_key=consumer_key,
    		consumer_secret=consumer_secret,
    		token=token,
    		token_secret=token_secret))
	t.statuses.update(status="Average data since last report\n{}".format(tweet))

while True:

        try:
		runReport()
            				
        except:
                print sys.exc_info()

        time.sleep(refreshSec)
